account/urls.py
from django.urls import path
from .views import SignIn, SignUp, SignOut, ManageAccount, GetAccountInfo, UpdateAccount, Update_Pic, UpdatePassword
from professional_profile.views import CreateProfessionalProfile


app_name = 'account'

urlpatterns = [
	path('sign_in/', SignIn, name='sign_in'),
	path('sign_up/', SignUp, name='sign_up'),
	path('signout', SignOut, name='sign_out'),
	path('manage/', ManageAccount, name='manage'),
	path('manage/edit/<str:token>', GetAccountInfo, name='edit_account'),
	path('manage/edit/ua/', UpdateAccount, name='update_account'),
	path('manage/edit/pp/<str:token>', Update_Pic, name='update_pic'),
	path('manage/edit/up/', UpdatePassword, name='update_pass'),
]

talents/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.views import Home
import debug_toolbar

app_name='main'

urlpatterns = [
    path('', Home, name='Home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('create/', include('professional_profile.urls')),
    path('confirm/', include('ConfirmAccount.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Components/Nav.html
{% load static %}
{% if request.user.is_authenticated %}
	<nav class="navbar navbar-expand-lg sticky-top nav_talents">
		<a href="{% url 'Home' %}">4-Talents</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#NavbarTalents" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
		</button>
		<div class="collapse navbar-collapse" id="NavbarTalents">
			<div class="navbar-nav ml-auto">
				<a href="{% url 'account:manage' %}" class="nav-link nav-item">Administrar Pérfil</a>
				<a href="#" class="nav-link nav-item">Ayuda</a>
				<a href="{% url 'account:sign_out' %}" class="nav-link nav-item">Cerrar Sesión</a>
			</div>
		</div>
	</nav>
    {% if request.path == '/create/create_prof/' %}
        {% else %}
        <div class="container">
            <div class="container-options">
                <ul class="nav">
                    <li class="nav-item"><a class="nav-link" href="#">Para empresas</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Para freelancers</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Para contratar</a></li>
                </ul>
            </div>
        </div>
    {% endif %}
	{% else %}
	<nav class="navbar navbar-expand-lg sticky-top nav_talents">
		<div class="container">
			<a href="{% url 'Home' %}">4-Talents</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#NavbarTalents" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"><i class="fas fa-bars"></i> </span>
			</button>
			<div class="collapse navbar-collapse" id="NavbarTalents">
				<div class="navbar-nav ml-auto">
					<a href="#" class="nav-link nav-item">Nosotros</a>
					<a href="#" class="nav-link nav-item">Ayuda</a>
					<a href="{% url 'account:sign_in' %}" class="nav-link nav-item">Iniciar Sesión</a>
				</div>
			</div>
		</div>
	</nav>
	<div class="container">
		<div class="container-options">
			<ul class="nav">
				<li class="nav-item"><a class="nav-link" href="#">Para empresas</a></li>
				<li class="nav-item"><a class="nav-link" href="#">Para freelancers</a></li>
				<li class="nav-item"><a class="nav-link" href="#">Para contratar</a></li>
			</ul>
		</div>
	</div>
{% endif %}

templates/Components/complements.html
{% load static %}
<footer>
	<script src="{% static 'js/Confirm/ConfirmAccount.js' %}"></script>
	<script src="{% static 'js/Account/UpdateAccount.js' %}"></script>
	<script src="{% static 'js/Account/UpdatePass.js' %}"></script>
</footer>

templates/Components/footer.html
<footer>
    <div class="container-fluid">
        <div class="container">
            <div class="container-logo">
                <a href="{% url 'Home' %}">4-Talents</a>
            </div>
            <div class="row mt-5">
                <div class="col-md-3 col-sm footer-settings">
                    <h2>4-Talents</h2>
                    <ul>
                        <li><a href="#">Como funciona?</a></li>
                        <li><a href="#">Empresas</a></li>
                        <li><a href="#">Buscar talentos</a></li>
                        <li><a href="#">Buscar empleos</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm footer-settings">
                    <h2>4-Talents / Lacayo & Asociados</h2>
                    <ul>
                        <li><a href=#>Nosotros</a></li>
                        <li><a href=#>Contacto</a></li>
                        <li><a href=#>Ayuda / Soporte</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm footer-settings">
                    <h2>4-Talents Social Media</h2>
                    <ul class="sociales">
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7415.849153200188!2d-86.2881006425349!3d12.12102015671646!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8f7155c429da1ff5%3A0x17651becf4ef4b31!2sOfiplaza%20El%20Retiro!5e0!3m2!1sen!2sni!4v1606195291778!5m2!1sen!2sni" width="100%" height="100%%" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
            </div>
        </div>
    </div>
</footer>