account/urls.py
from django.urls import path
from .views import SignIn, SignUp, SignOut, ManageAccount, GetAccountInfo, UpdateAccount, Update_Pic, UpdatePassword
from professional_profile.views import CreateProfessionalProfile


app_name = 'account'

urlpatterns = [
	path('sign_in/', SignIn, name='sign_in'),
	path('sign_up/', SignUp, name='sign_up'),
	path('signout', SignOut, name='sign_out'),
	path('manage/', ManageAccount, name='manage'),
	path('manage/edit/<str:token>', GetAccountInfo, name='edit_account'),
	path('manage/edit/ua/', UpdateAccount, name='update_account'),
	path('manage/edit/pp/<str:token>', Update_Pic, name='update_pic'),
	path('manage/edit/up/', UpdatePassword, name='update_pass'),
]

talents/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.views import Home
import debug_toolbar

app_name='main'

urlpatterns = [
    path('', Home, name='Home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('create/', include('professional_profile.urls')),
    path('confirm/', include('ConfirmAccount.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/SignIn/SignIn.html
{% extends "base.html" %}
{% load static %}

{#Creating title#}
{% block title %}
	Sign In
{% endblock title %}

{#Creating Content#}
{% block content %}
		<div class="row signin-height">
			<div class="col-sm col-md-4">
				<div class="container-title">
					<h2>4-Talents</h2>
				</div>
				<div class="container-form">
					<form method="POST">
						<div class="form-row">
							<label>Usuario</label>
							{{ forms.username }}
						</div>
						<div class="form-row">
							<label>Contraseña</label>
							{{ forms.password }}
						</div>
						<div class="container-sign-btn mt-3">
							{% csrf_token %}
							<button type="button" class="btn btn-success sign-btn" id="signin-btn" onclick="SignIn()">Iniciar Sesión</button>
						</div>
					</form>

					<div class="container-recoverypass-link mt-5">
						<a href="#">¿Olvidaste tu contraseña?</a>
					</div>
					<hr/>

					<div class="container-signup-link">
						<a href="{% url 'account:sign_up' %}">¿Aún no estás registrado? <span>¡Hazlo ahora!</span></a><br/>
						<a href="{% url 'Home' %}">Volver a Inicio</a>
					</div>
				</div>
			</div>

			<div class="col-md-8  signin-right-screen">
				<div class="container-img-right-screen">
					<img src="{% static 'img/sign_in_2.png' %}" class="img-fluid" alt="Sign In">
				</div>
			</div>
		</div>
{% endblock content %}